// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/nabilulilalbab/streamv2",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/nabilulilalbab/streamv2/issues",
            "email": "nabilulilalbab@github.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/featured": {
            "get": {
                "description": "Retrieve list of featured movies from IDLIX homepage (excluding TV series)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "movies"
                ],
                "summary": "Get featured movies",
                "responses": {
                    "200": {
                        "description": "Featured movies retrieved successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.FeaturedMoviesResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check if API is running and get version information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "API is healthy",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/proxy": {
            "get": {
                "description": "Proxy streaming requests to bypass CORS restrictions",
                "produces": [
                    "application/x-mpegURL",
                    "video/MP2T"
                ],
                "tags": [
                    "proxy"
                ],
                "summary": "Proxy M3U8/TS requests",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target URL to proxy",
                        "name": "url",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Stream content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid URL",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Proxy error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/subtitle/download": {
            "get": {
                "description": "Download subtitle file with CORS support and optional format conversion",
                "produces": [
                    "text/plain",
                    "text/vtt"
                ],
                "tags": [
                    "subtitle"
                ],
                "summary": "Download subtitle file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Subtitle URL",
                        "name": "url",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Target format (srt or vtt)",
                        "name": "format",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Custom filename",
                        "name": "filename",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Subtitle file content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid parameters",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Download or conversion error",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/subtitle/search": {
            "get": {
                "description": "Get subtitle tracks for a video with optional language filter",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subtitle"
                ],
                "summary": "Search subtitle tracks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Video URL",
                        "name": "url",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Language filter (case-insensitive, partial match)",
                        "name": "language",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Subtitles found",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.SubtitleSearchResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid parameters",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get subtitles",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/video/info": {
            "post": {
                "description": "Get complete video information including M3U8 streams, quality variants, and subtitles",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "videos"
                ],
                "summary": "Get video information",
                "parameters": [
                    {
                        "description": "Video URL request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VideoInfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Video info retrieved successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.VideoInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "$ref": "#/definitions/models.ErrorInfo"
                },
                "message": {
                    "type": "string",
                    "example": "Success"
                },
                "status": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "models.ErrorInfo": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "ERROR_CODE"
                },
                "details": {
                    "type": "string",
                    "example": "Detailed error message"
                }
            }
        },
        "models.FeaturedMoviesResponse": {
            "type": "object",
            "properties": {
                "movies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Movie"
                    }
                }
            }
        },
        "models.Movie": {
            "type": "object",
            "properties": {
                "poster": {
                    "type": "string",
                    "example": "https://image.tmdb.org/t/p/w185/poster.jpg"
                },
                "title": {
                    "type": "string",
                    "example": "Example Movie (2024)"
                },
                "type": {
                    "type": "string",
                    "example": "movie"
                },
                "url": {
                    "type": "string",
                    "example": "https://tv12.idlixku.com/movie/example-2024/"
                },
                "year": {
                    "type": "string",
                    "example": "2024"
                }
            }
        },
        "models.SubtitleInfo": {
            "type": "object",
            "properties": {
                "available": {
                    "type": "boolean",
                    "example": true
                },
                "tracks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SubtitleTrack"
                    }
                }
            }
        },
        "models.SubtitleSearchResponse": {
            "type": "object",
            "properties": {
                "filtered": {
                    "type": "boolean",
                    "example": true
                },
                "subtitles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SubtitleTrackInfo"
                    }
                },
                "total": {
                    "type": "integer",
                    "example": 2
                },
                "video_id": {
                    "type": "string",
                    "example": "163426"
                },
                "video_name": {
                    "type": "string",
                    "example": "Crime 101 (2026)"
                }
            }
        },
        "models.SubtitleTrack": {
            "type": "object",
            "properties": {
                "format": {
                    "type": "string",
                    "example": "srt"
                },
                "language": {
                    "type": "string",
                    "example": "Bahasa"
                },
                "url": {
                    "type": "string",
                    "example": "https://g5.wiseacademia.asia/r/xyz.jpg"
                }
            }
        },
        "models.SubtitleTrackInfo": {
            "type": "object",
            "properties": {
                "download_url": {
                    "type": "string",
                    "example": "/api/v1/subtitle/download?url=..."
                },
                "format": {
                    "type": "string",
                    "example": "srt"
                },
                "language": {
                    "type": "string",
                    "example": "Bahasa"
                },
                "url": {
                    "type": "string",
                    "example": "https://g5.wiseacademia.asia/r/xyz.jpg"
                }
            }
        },
        "models.VariantPlaylist": {
            "type": "object",
            "properties": {
                "bandwidth": {
                    "type": "integer",
                    "example": 1510000
                },
                "id": {
                    "type": "string",
                    "example": "0"
                },
                "resolution": {
                    "type": "string",
                    "example": "1920x1080"
                },
                "uri": {
                    "type": "string",
                    "example": "https://jeniusplay.com/hls/hash123/1080p.m3u8"
                }
            }
        },
        "models.VideoInfo": {
            "type": "object",
            "properties": {
                "embed_url": {
                    "type": "string",
                    "example": "https://jeniusplay.com/video/hash123"
                },
                "is_variant_playlist": {
                    "type": "boolean",
                    "example": true
                },
                "m3u8_url": {
                    "type": "string",
                    "example": "https://jeniusplay.com/cdn/hls/hash123/master.m3u8"
                },
                "poster": {
                    "type": "string",
                    "example": "https://image.tmdb.org/t/p/w185/poster.jpg"
                },
                "subtitle": {
                    "$ref": "#/definitions/models.SubtitleInfo"
                },
                "variants": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.VariantPlaylist"
                    }
                },
                "video_id": {
                    "type": "string",
                    "example": "163426"
                },
                "video_name": {
                    "type": "string",
                    "example": "Crime 101 (2026)"
                }
            }
        },
        "models.VideoInfoRequest": {
            "type": "object",
            "required": [
                "url"
            ],
            "properties": {
                "url": {
                    "type": "string",
                    "example": "https://tv12.idlixku.com/movie/crime-101-2026/"
                }
            }
        }
    },
    "tags": [
        {
            "description": "System health and status endpoints",
            "name": "system"
        },
        {
            "description": "Movie browsing and discovery endpoints",
            "name": "movies"
        },
        {
            "description": "Video information and streaming endpoints",
            "name": "videos"
        },
        {
            "description": "Subtitle download and search endpoints",
            "name": "subtitle"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "IDLIX API",
	Description:      "RESTful API for IDLIX video streaming platform. Provides endpoints for scraping movie data, M3U8 streams, and video variants.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
